# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.50.2"
  #, virtualbox__intnet: true
  # config.vm.network "public_network", bridge: "wlp3s0"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "file", source: "files/kubeadm-kuberouter-all-features.yaml", destination: "~/kubeadm-kuberouter-all-features.yaml"

  config.vm.provision "shell", path: "../scripts/system_update.sh"
  config.vm.provision "shell", path: "../scripts/install_docker.sh"
  config.vm.provision "shell", path: "../scripts/install_kubernetes.sh"

  config.vm.provision "shell", path: "scripts/k8s_setup.sh"
  config.vm.provision "shell", path: "scripts/user_config.sh", privileged: false

  config.vm.provision "shell" do |x|
    x.inline = "kubectl apply -f kubeadm-kuberouter-all-features.yaml"
    x.inline = "echo $(id -u)"
  end
end
